### ISSUE TITLE
Finished environment mapping is too bright and needs to rotate 180 degrees

### ISSUE THREAD

**Issue by joekay** [svtek/ARKitEnvironmentMapper#6]
Hi!

Must start off by saying that this tool is amazing. 

Im having a problem with my finished environment mapping. As the title says, the brightness is too high, is this a problem you are having aswell? The objects are really standing out in the scene. The second issue that I am having is that the environment map needs to be rotated horizontally 180 degrees, which now seems like the alignment of the env map is that of how it was fed to the camera.

Have you encountered these problems before?

Cheers

**Comment by halileohalilei** [comment]
Hey @joekay, can you share the generated environment map or a screenshot of the resulting 3D objects on your scene? There is currently an issue about handling light and I've been working on it for a while, it will hopefully be fixed in the next release. But I'm not sure if it's the same thing that you are experiencing.

I don't know about the environment map being rotated though, I had not encountered that one before. I will have a look at it.

**Comment by joekay** [comment]
Hi again and thank you for your answer.

I solved the light issue. I am experimenting with different type of environment maps and was using the base case Apple example, where they include some fiddling with the light environment intensity. I lowered the intensity for the scene light intensity which gave me better results with the realtime env map.

The second issue is still partially there, where the environment map looks good in some angles but not all. Maybe its just limitations with ARKit that can't be avoided if you have experienced the same? Posting two pictures for reference where I have placed a metallic sphere in the room. In the first picture, the glass table is about in the right alignment, but not with the tv in the second picture.

![29681300_10155591259888250_1378590148_o](https://user-images.githubusercontent.com/9570859/37935212-fad76f2a-3150-11e8-8305-8434de3ba5b2.jpg)
![29527657_10155591259938250_1366591140_o](https://user-images.githubusercontent.com/9570859/37935211-faa264f6-3150-11e8-9d68-2906d0c99e32.jpg)

(Both pictures are from the same run of the app)
